# title: De AutCast
# email: autcast@myautisticself.nl
# description: >- # this means to ignore newlines until "baseurl:"
#   De AutCast is een podcast over autisme en neurodiversiteit. Een zoektocht
#   naar wat autisme nu betekend voor mensen en hoe we de wereld beter om kunnen
#   laten gaan met neurodiversiteit. 
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: de_aut

# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# remote_theme             : "mmistakes/minimal-mistakes@4.21.0"

minimal_mistakes_skin    : "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site Settings
locale                   : "nl-NL"
title                    : "De AutCast"
title_separator          : "-"
subtitle                 : "Een neurodiverse podcast"
name                     : &name "David Westerink" # &name is a YAML anchor which can be *referenced later
description              : &description >- # this means to ignore newlines until "baseurl:"
  De AutCast is een podcast over autisme en neurodiversiteit. Een zoektocht
  naar wat autisme nu betekend voor mensen en hoe we de wereld beter om kunnen
  laten gaan met neurodiversiteit. 
url                      : https://autcast.nl # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
baseurl                  : "/" # the subpath of your site, e.g. "/blog"
repository               : "davidakachaos/deautcast"
teaser                   : "/assets/img/autcast2.png" # path of fallback teaser image, e.g. "/assets/images/500x300.png"
logo                     : "/assets/img/autcast2.png" # path of logo image to display in the masthead, e.g. "/assets/images/88x88.png"
masthead_title           : # overrides the website title displayed in the masthead, use " " for no title
# breadcrumbs            : false # true, false (default)
words_per_minute         : 200
comments:
  provider               : "staticman_v2" # false (default), "disqus", "discourse", "facebook", "staticman_v2", "staticman", "utterances", "custom"
  disqus:
    shortname            :
  staticman:
    endpoint: "https://staticman-dw.herokuapp.com/v2/entry/"
    branch: "source"
  discourse:
    server               : # https://meta.discourse.org/t/embedding-discourse-comments-via-javascript/31963 , e.g.: meta.discourse.org
  facebook:
    # https://developers.facebook.com/docs/plugins/comments
    appid                :
    num_posts            : # 5 (default)
    colorscheme          : # "light" (default), "dark"
  utterances:
    theme                : # "github-light" (default), "github-dark"
    issue_term           : # "pathname" (default)
# reCaptcha configuration info: the exact same site key and *encrypted* secret that you used in staticman.yml
# I personally don't think the secret needs to be included in the generated site, but the staticman API bridge uses
# it to ensure the site configuration and bridge configuration match (but why not just compare the site key?)
reCaptcha:
  siteKey: 6LcfM30eAAAAAHMEWsEGmVB36fZ24nAr9B6Eh6qM
  secret: bJGZufPapmBwKApYfauj1XOdZJZZMEHeqi26bT1ccO6jFRYME7hgWrC52xhJCT622w4pQi3qAw/E49Ek85UK00efuo2WZsiijM2yCw/UTUwxqSycAz0biV9pEg9Mu60KpzPr/gQUAAcSa5kQsuX3xOXUFznObEnZ8+LbnJV19DemRUnxKS38odKLqlzfG2pAGpJNtzC5ObB5vLeTDcu8ArlGkI1acxFNIdV7/Yb5M+Bx/hs4Q23dIalz2HDZkYwoD1BCcTBoft/pgBXWidSbsu+pT2rritrwWnYtOMkcHJKCooJqQD2js0aZmtdWphr7bu2QWmN56fH6Zs0H8gsIjw==

# staticman:
#   branch: "source"
staticman_url: https://staticman-dw.herokuapp.com/v2/entry/davidakachaos/deautcast/source/comments

atom_feed:
  path                   : # blank (default) uses feed.xml

# search                   : true # true, false (default)
# search_full_content      : true # true, false (default)
# search_provider          : algolia # lunr (default), algolia
# algolia:
#   application_id         : QB6HVGBSBA # YOUR_APPLICATION_ID
#   index_name             : minimal_mistakes # YOUR_INDEX_NAME
#   search_only_api_key    : 9d5014e5bbc77372547bce778dfa5663 # YOUR_SEARCH_ONLY_API_KEY
#   powered_by             : true # true (default), false
#   files_to_exclude:
#     - _posts/2017-11-28-post-exclude-search.md

# SEO Related
google_site_verification : "" # Replace this with your ID, or delete
bing_site_verification   :
yandex_site_verification :
naver_site_verification  :

# Social Sharing
twitter:
  username               : &twitter "de_aut"
facebook:
  username               : &facebook "deautcast"
  app_id                 :
  publisher              :
og_image                 : "/assets/images/site-logo.png" # Open Graph/Twitter default site image
# For specifying social profiles, used in _includes/seo.html
# - https://developers.google.com/structured-data/customize/social-profiles
social:
  type                   : "Organization" # Person or Organization (defaults to Person)
  name                   : # If the user or organization name differs from the site's name
  links: # An array of links to social media profiles
    - "https://twitter.com/de_aut"
    - "https://www.facebook.com/deautcast"
    - "https://www.instagram.com/deautcast/"

# Analytics
analytics:
  provider               : "google-gtag" # false (default), "google", "google-universal", "google-gtag", "custom"
  google:
    tracking_id          : "G-67G4LKLC3J" # Replace this with your ID, or delete
    anonymize_ip         : true


# Site Author
author:
  name             : *name # *name is a YAML reference pointing to the &anchor earlier
  avatar           : "/assets/img/profile2.jpg"
  bio              : "Je gastheer in de wondere wereld van autisme"
  location         : "Heerenveen, NL"
  links:
    - label: "My Autistic Self"
      icon: "fas fa-fw fa-link"
      url: "https://myautisticself.nl"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/WesterinkDavid"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook"
      url: "https://www.facebook.com/myautisticself"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/deautcast"


# Site Footer
footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/de_aut"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook"
      url: "https://fb.me/DeAutCast"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/deautcast"


# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - .bitly_cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp
  - bin
  - .bundle
  - deploy.sh
  - package-lock.json
  - staticman.yml
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Defaults
defaults:
  - # _posts
    scope:
      path: ""
      type: "posts"
    values: &posts
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      podcast_episode: 
      tags: 
  # _pages
  - 
    scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

jekyll_compose:
  default_front_matter:
    drafts: 
      <<: *posts
    posts:
      <<: *posts


# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style


# Outputting
permalink: /:categories/:title/
# paginate: 5 # amount of posts to show
# paginate_path: /page:num/
timezone: Europe/Amsterdam # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones


# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-archives
  - jekyll-redirect-from

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-archives


# Archives
#  Type
#  - GitHub Pages compatible archive pages built with Liquid ~> type: liquid (default)
#  - Jekyll Archives plugin archive pages ~> type: jekyll-archives
#  Path (examples)
#  - Archive page should exist at path when using Liquid method or you can
#    expect broken links (especially with breadcrumbs enabled)
#  - <base_path>/tags/my-awesome-tag/index.html ~> path: /tags/
#  - <base_path>/categories/my-awesome-category/index.html ~> path: /categories/
#  - <base_path>/my-awesome-category/index.html ~> path: /
category_archive:
  type: jekyll-archives
  path: /categories/
tag_archive:
  type: jekyll-archives
  path: /tags/
# https://github.com/jekyll/jekyll-archives
jekyll-archives:
  enabled:
    - categories
    - tags
  layouts:
    category: archive-taxonomy
    tag: archive-taxonomy
  permalinks:
    category: /categories/:name/
    tag: /tags/:name/


# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  blanklines: true
  ignore:
    envs: development
